# -*- coding: utf-8 -*-
"""Copy of Coffee_Reccomendation_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrPSgm9OTLdkjhPVavm7LqP7bYOLpV3W
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import random as rand

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack

import matplotlib.pyplot as plt

users_data_names= ['userId','email','passwordHash','firstName','lastName']
udata = pd.read_csv('users_large.csv',
                   names = users_data_names)
udata.head()

taste_profiles_data_names = ['temperature',	'flavor_1',	'flavor_2',	'flavor_3',	'drinkType_1',	'drinkType_2',	'drinkType_3',	'milk']
tpdata = pd.read_csv('taste_profiles_large.csv',
                   names = taste_profiles_data_names)
tpdata.head()

drinks_data_names = ['drinkName',	'drinkType',	'temperature',	'milk',	'flavor 1', 'flavor 2',	'cost',	'cals', 'coffeeShop']
drdata = pd.read_csv('drinks_large.csv',
                   names = drinks_data_names)
drdata.head()

order_history_data_names = ['userId',	'drink',	'cafeName']
orderhdata = pd.read_csv('order_history_large.csv',
                   names = order_history_data_names)
orderhdata.head()

users = pd.read_csv("users_large.csv")
taste = pd.read_csv("taste_profiles_large.csv")
drinks = pd.read_csv("drinks_large.csv")

#turning the data into bag-of-words
def user_to_text(row):
    return " ".join([
        row["flavor_1"],
        row["flavor_2"],
        row["flavor_3"],
        row["drinkType_1"],
        row["drinkType_2"],
        row["drinkType_3"],
    ])

taste["text_features"] = taste.apply(user_to_text, axis=1)

def drink_to_text(row):
    return " ".join([
        row["flavor 1"],
        row ["flavor 2"],
        row["drinkType"],
    ])

drinks["text_features"] = drinks.apply(drink_to_text, axis=1)

#TF-IDF vectorization

vectorizer = TfidfVectorizer()

combined_text = pd.concat([
    taste["text_features"],
    drinks["text_features"]
])

tfidf_matrix = vectorizer.fit_transform(combined_text)

#split the text back into user and drink
user_tfidf = tfidf_matrix[:len(taste)]
drink_tfidf = tfidf_matrix[len(taste):]

#OHE for binary data (non categorical)

cat_encoder = OneHotEncoder()

combined_cat = pd.concat([
    taste[["temperature", "milk"]],
    drinks[["temperature", "milk"]]
])

cat_encoder.fit(combined_cat)

user_cat = cat_encoder.transform(taste[["temperature", "milk"]])
drink_cat = cat_encoder.transform(drinks[["temperature", "milk"]])

#recc algo via cosine similarity

user_vectors = hstack([user_tfidf, user_cat])
drink_vectors = hstack([drink_tfidf, drink_cat])

def recommend_drinks(user_id, top_k=5):
    user_idx = taste.index[taste["userId"] == user_id][0]

    similarities = cosine_similarity(
        user_vectors[user_idx],
        drink_vectors
    )[0]

    top_indices = similarities.argsort()[-top_k:][::-1]

    return drinks.iloc[top_indices][
        ["drinkName", "drinkType", "milk"]
    ]

recommend_drinks("anikalovescoffee", top_k=3)
#recommend_drinks("advithiK", top_k=3)
#recommend_drinks("kelseykoffee", top_k=3)